export default [
  {
    name: 'Anđelić Ranko',
    title: 'Master in Illustration and Animation',
    institution: 'Kingston University, United Kingdom',
    speciality: 'Graphic and Multimedia Design',
    photo: '/assets/images/staff/placeholder.png',
  }, {
    name: 'Aščerić Damir',
    title: 'Master of Business Administration',
    institution: 'Cardiff Metropolitan University, United Kingdom',
    speciality: 'Economics and Business',
    photo: '/assets/images/staff/placeholder.png',
  }, {
    name: 'Agić Belmir',
    title: 'Master of Management in Strategic Information Management',
    institution: 'Faculty of Economics, University of Sarajevo, Bosnia and Herzegovina',
    speciality: 'Economics and Business',
    photo: '/assets/images/staff/placeholder.png',
  }, {
    name: 'Baraković Sabina',
    title: 'Doctor of Philosophy in Electrical Engineering',
    institution: 'Faculty of Electrical Engineering and Computing, University in Zagreb, Croatia',
    speciality: 'Computer and Information Technology',
    photo: '/assets/images/staff/placeholder-f.png',
  }, {
    name: 'Bezdrob Muamer',
    title: 'Doctor of Economic Sciences in Management',
    institution: 'School of Economics, University of Sarajevo, Bosnia and Herzegovina',
    speciality: 'Economics and Business',
    photo: '/assets/images/staff/placeholder.png',
  }, {
    name: 'Božanović Olja',
    title: 'Diploma in Computer Scieneces and Electrical Engineering',
    institution: 'Sarajevo School of Science and Technology, Bosnia and Herzegovina',
    speciality: 'Computer and Information Technology',
    photo: '/assets/images/staff/placeholder-f.png',
  }, {
    name: 'Crneta Mersida',
    title: 'Master of English Language and Literature',
    institution: 'Faculty of Philosoph, University of Sarajevo, Bosnia and Herzegovina',
    speciality: 'English Language and Literature',
    photo: '/assets/images/staff/placeholder.png',
  }, {
    name: 'Čengić Arif',
    title: 'Diploma in Electrical Engineering Telecommunications',
    institution: 'Faculty of Electrical Engineering, University of Sarajevo, Bosnia and Herzegovina',
    speciality: 'Computer and Information Technology',
    photo: '/assets/images/staff/placeholder.png',
  }, {
    name: 'Ćurčić Fuad',
    title: 'Doctor of Philosophy (Ph.D) in Management and Leadership Studies',
    institution: 'International University of Sarajevo, Bosnia and Herzegovina',
    speciality: 'Computer and Information Technology',
    photo: '/assets/images/staff/placeholder.png',
  }, {
    name: 'Dardagan Amer',
    title: 'Master in History',
    institution: 'Faculty of Philosophy, University of Sarajevo, Bosnia and Herzegovina',
    speciality: 'General History',
    photo: '/assets/images/staff/placeholder.png',
  }, {
    name: 'Dautović Kenan',
    title: 'Doctor of Political Science',
    institution: 'Faculty of Political Science of University of Sarajevo, Bosnia and Hercegovina',
    speciality: 'Political Science',
    photo: '/assets/images/staff/placeholder.png',
  }, {
    name: 'Dedić Velimir',
    title: 'Doctor of Philosophy in Economy',
    institution: 'Faculty for Trade and Banking, University “Braća Karić”, Republic of Serbia',
    speciality: 'Computer and Information Technology',
    photo: '/assets/images/staff/placeholder.png',
  }, {
    name: 'Delalić Selma',
    title: 'Doctor of Political Sciences',
    institution: 'Faculty of Political Science, University of Sarajevo, Bosnia and Herzegovina',
    speciality: 'Political Science',
    photo: '/assets/images/staff/placeholder-f.png',
  }, {
    name: 'Džamalija Adi',
    title: 'Master of Law, State and International Public Law',
    institution: 'Faculty of Law, University of Sarajevo, Bosnia and Herzegovina',
    speciality: 'General Law',
    photo: '/assets/images/staff/placeholder.png',
  }, {
    name: 'Džanić Enis',
    title: 'Doctor of Philosophy in Economics',
    institution: 'International University Philip Noel Baker Sarajevo, Bosnia and Herzegovina',
    speciality: 'Economics and Business',
    photo: '/assets/images/staff/placeholder.png',
  }, {
    name: 'Đaltur Vahidin',
    title: 'Master of Science in Information Technology',
    institution: 'International Burch University, Bosnia and Hercegovina',
    speciality: 'Computer and Information Technology',
    photo: '/assets/images/staff/placeholder.png',
  }, {
    name: 'Festić Mustafa',
    title: 'Doctor of Philosophy in Economics and Economic Policy',
    institution: 'University of Zagreb, Croatia',
    speciality: 'Rector',
    photo: '/assets/images/staff/placeholder.png',
  }, {
    name: 'Gavranović Nedim',
    title: 'Doctor of Philosophy in Actuarial Science',
    institution: 'City University of London, United Kingdom',
    speciality: 'Mathematics – Statistics',
    photo: '/assets/images/staff/placeholder.png',
  }, {
    name: 'Gavrić Sabrina',
    title: 'Master of Laws in International Business Law',
    institution: 'Central European University, Hungary',
    speciality: 'General Law',
    photo: '/assets/images/staff/placeholder-f.png',
  }, {
    name: 'Hadžimehmedović Amir',
    title: 'Doctor of Laws in International Business Law',
    institution: 'Faculty of Electrical Engineering, University of Tuzla, Bosnia and Hercegovina',
    speciality: 'Computer and Information Technology',
    photo: '/assets/images/staff/placeholder.png',
  }, {
    name: 'Hadžiomerspahić Anur',
    title: 'Master in Graphic Design',
    institution: 'Academy of Fine Arts, University of Sarajevo, Bosnia and Herzegovina',
    speciality: 'Graphic and Multimedia Design',
    photo: '/assets/images/staff/placeholder.png',
  }, {
    name: 'Hivziefendić Jasna',
    title: 'Doctor of Technical Sciences in Electrical Engineering',
    institution: 'Faculty of Electrical Engineering, University of Tuzla, Bosnia and Herzegovina',
    speciality: 'Computer and Information Technology',
    photo: '/assets/images/staff/placeholder-f.png',
  }, {
    name: 'Hodžić Migdat',
    title: 'Doctor of Electrical Engineering an Computer Science',
    institution: 'Santa Clara University, California, USA',
    speciality: 'Computer and Information Technology',
    photo: '/assets/images/staff/placeholder.png',
  }, {
    name: 'Hodžić Nermin',
    title: 'Master of Science in Electrical Engineering',
    institution: 'Faculty of Electrical Engineering, University of Tuzla, Bosnia and Herzegovina',
    speciality: 'Computer and Information Technology',
    photo: '/assets/images/staff/placeholder.png',
  }, {
    name: 'Idrizović Kenan',
    title: 'Master of Laws in Comparative Constitutional Law',
    institution: 'Central European University, Hungary',
    speciality: 'General Law',
    photo: '/assets/images/staff/placeholder.png',
  }, {
    name: 'Iljazović Jasmila',
    title: 'Master of Laws in International Business Law',
    institution: 'Central European University, Hungary',
    speciality: 'General Law',
    photo: '/assets/images/staff/placeholder-f.png',
  }, {
    name: 'Jukan Admir',
    title: 'Master of Technical Sciences in Electrical Engineering',
    institution: 'Faculty of Electrical Engineering, University of Tuzla, Bosnia and Herzegovina',
    speciality: 'Computer and Information Technology',
    photo: '/assets/images/staff/placeholder.png',
  }, {
    name: 'Kirlić-Hasović Ajla',
    title: 'Master of Computer Science',
    institution: 'Faculty of Natural Sciences and Mathematics, University of Sarajevo, Bosnia and Hercegovina',
    speciality: 'Mathematics - Statistics',
    photo: '/assets/images/staff/placeholder-f.png',
  }, {
    name: 'Kordić-Grujić Maja',
    title: 'Master of Science in Multimedia with concentration in Hypermedia and Electronic Publishing',
    institution: 'University of Paris, France',
    speciality: 'Graphic and Multimedia Design',
    photo: '/assets/images/staff/placeholder-f.png',
  }, {
    name: 'Kulenović Feđa',
    title: 'Diploma in Comparative Literature and Library',
    institution: 'Faculty of Philosophy, University of Sarajevo, Bosnia and Herzegovina',
    speciality: 'Library/Information Literacy (course)',
    photo: '/assets/images/staff/placeholder.png',
  }, {
    name: 'Matar Šadi',
    title: 'Master of Science in Computer Engineering',
    institution: 'Faculty of Philosophy, University of Sarajevo, Bosnia and Hercegovina',
    speciality: 'Computer and Information Technology',
    photo: '/assets/images/staff/placeholder.png',
  }, {
    name: 'McMickle Padraic',
    title: 'Master of Business (International Business) / Master of Philosophy in Management Studies',
    institution: 'Bond University, Australia / University of Exeter, United Kingdom',
    speciality: 'Economics and Business',
    photo: '/assets/images/staff/placeholder.png',
  }, {
    name: 'Mehanović Dina',
    title: 'Diploma in Mathematics',
    institution: 'Faculty of Natural Science and Mathematics Department of Mathematics, University of Tuzla, Bosnia and Herzegovina',
    speciality: 'Mathematics – Statistics',
    photo: '/assets/images/staff/placeholder-f.png',
  }, {
    name: 'Mesbah Laurent',
    title: 'Doctor of Philosophy in Biology',
    institution: 'The Free University of Amsterdam, Netherlands',
    speciality: 'Environmental Protection',
    photo: '/assets/images/staff/placeholder.png',
  }, {
    name: 'Mukić Amila',
    title: 'Diploma in English Language and Literature',
    institution: 'Faculty of Philosophy, University of Tuzla, Bosnia and Herzegovina',
    speciality: 'English Language and Literature',
    photo: '/assets/images/staff/placeholder-f.png',
  }, {
    name: 'Murtezić Arben',
    title: 'Master of Science in International Criminal Justice',
    institution: 'University of Portsmouth, United Kingdom',
    speciality: 'General Law',
    photo: '/assets/images/staff/placeholder.png',
  }, {
    name: 'Njemčević Faris',
    title: 'Master of Economic Sciences in Business Economy',
    institution: 'Faculty of Economics, University of Sarajevo, Bosnia and Herzegovina',
    speciality: 'Economics and Business',
    photo: '/assets/images/staff/placeholder.png',
  }, {
    name: 'Obučić Engin',
    title: 'Master of Marketing Management',
    institution: 'University of Canberra, Australia',
    speciality: 'Economics and Business',
    photo: '/assets/images/staff/placeholder.png',
  }, {
    name: 'Pašić Ibrahim',
    title: 'Doctor of History Sciences',
    institution: 'Faculty of Philosophy, University of Prishtina, Kosovo',
    speciality: 'General History',
    photo: '/assets/images/staff/placeholder.png',
  }, {
    name: 'Pejić Alisa',
    title: 'Diploma in English Language and Literature',
    institution: 'Faculty of Philosophy, University of Tuzla, Bosnia and Hercegovina',
    speciality: 'English Language and Literature',
    photo: '/assets/images/staff/placeholder-f.png',
  }, {
    name: 'Pešto Haris',
    title: 'Doctor of Economic Sciences',
    institution: 'Faculty for Business and Financial Studies, University of Banja Luka, Bosnia and Herzegovina',
    speciality: 'Economics and Business',
    photo: '/assets/images/staff/placeholder.png',
  }, {
    name: 'Pleho Jasna',
    title: 'Master of Science in Electrical Engineering in Computing and Information Technology',
    institution: 'Faculty of Electrical Engineering, University of Sarajevo, Bosnia and Herzegovina',
    speciality: 'Computer and Information Technology',
    photo: '/assets/images/staff/placeholder-f.png',
  }, {
    name: 'Putica Sanda',
    title: 'Master in State Management and Humanitarian Affairs',
    institution: 'University of Rome “La Sapienza” – University of Sarajevo – University of Belgrade',
    speciality: 'Economics and Business',
    photo: '/assets/images/staff/placeholder-f.png',
  }, {
    name: 'Rimac-Bjelobrk Maja' ,
    title: 'Master in State Management and Humanitarian Affairs',
    institution: 'University of Rome “La Sapienza” – University of Sarajevo – University of Belgrade',
    speciality: 'General Law',
    photo: '/assets/images/staff/placeholder-f.png',
  }, {
    name: 'Rizvo Samir',
    title: 'Doctor of Legal Sciences in International Law',
    institution: 'American School of Government, American University in Bosnia and Herzegovina, Bosnia and Herzegovina',
    speciality: 'General Law',
    photo: '/assets/images/staff/placeholder.png',
  }, {
    name: 'Salkić Nermin',
    title: 'Diploma in History of Art',
    institution: 'Faculty of Philosophy, University of Sarajevo, Bosnia and Herzegovina',
    speciality: 'Graphic and Multimedia Design',
    photo: '/assets/images/staff/placeholder.png',
  }, {
    name: 'Savatić Alen',
    title: 'Master of Managment Information Systems',
    institution: 'School of Technology, Hodges University, USA',
    speciality: 'Computer and Information Technology',
    photo: '/assets/images/staff/placeholder.png',
  }, {
    name: 'Selimović Jasmila',
    title: 'Master in European Studies',
    institution: 'Center for Interdisciplinary Postgraduate Studies, University of Sarajevo, Bosnia and Herzegovina',
    speciality: 'Economics and Business',
    photo: '/assets/images/staff/placeholder-f.png',
  }, {
    name: 'Smajević Amir',
    title: 'Master of Science in Electrical Engineering Science in Computer and Information Technology',
    institution: 'Faculty of Electrical Engineering, University of Sarajevo, Bosnia and Herzegovina',
    speciality: 'Computer and Information Technology',
    photo: '/assets/images/staff/placeholder.png',
  }, {
    name: 'Smajić Nejra',
    title: 'Master of Laws in European Union Law',
    institution: 'Faculty of Law, University of Sarajevo, Bosnia and Herzegovina',
    speciality: 'General Law',
    photo: '/assets/images/staff/placeholder-f.png',
  }, {
    name: 'Tanović Anel',
    title: 'Doctor of Technical Sciences in Information Systems',
    institution: 'Faculty of Electrical Engineering, University of Sarajevo, Bosnia and Herzegovina',
    speciality: 'Computer and Information Technology',
    photo: '/assets/images/staff/placeholder.png',
  }, {
    name: 'Vekić Branko',
    title: 'Diploma in Graphic Design',
    institution: 'Academy of Fine Arts, University in Sarajevo, Bosnia and Herzegovina',
    speciality: 'Graphic and Multimedia Design',
    photo: '/assets/images/staff/placeholder.png',
  },
];
